use dbmysql;
create table customer(cno int(10), cname varchar(20),ccity varchar(20),cpostalid int(10),ccountry varchar(20));
desc customer;
insert into customer values(1 ,'Alfred',' Berlin' ,12209, 'Germany');
insert into customer values(2 ,'Ana',' México', 05021,' Mexico');
insert into customer values(3 ,'Antonio',' México', 05023 ,'Mexico');
insert into customer values(4 ,'Harry','London', 001123,' UK');
insert into customer values(5,'Sierra' ,'Luleå',1-95822 ,'Sweden');
select * from customer;
SELECT * FROM Customer ORDER BY ccountry;
SELECT COUNT(cno), ccountry FROM Customer GROUP BY ccountry;
SELECT COUNT(cno), ccountry FROM Customer GROUP BY ccountry HAVING COUNT(cno) > 5;
SELECT COUNT(cno), ccountry FROM Customer GROUP BY ccountry HAVING COUNT(cno) > 5 ORDER BY COUNT(cno) DESC;
SELECT COUNT(cno), ccountry FROM Customer GROUP BY ccountry HAVING COUNT(cno) < 5 ORDER BY COUNT(cno);
select cname from customer order by cname desc; 
select cname from customer order by cname asc; 
select count(*),ccountry from customer;
SELECT COUNT(*), ccountry FROM Customer GROUP BY ccity HAVING COUNT(ccity) > 1 ORDER BY COUNT(cno) DESC;
SELECT COUNT(*), ccountry FROM Customer GROUP BY ccity HAVING COUNT(ccity) > 1 ORDER BY COUNT(cno);
select * from customer where ccountry like 'mexico%';
select * from customer where ccountry like 'mexico%';
select * from customer where ccountry like '%mexico%';
desc customer;
insert into customer(cno)values(8);
alter table customer modify cname varchar(10)not null;
ALTER TABLE customer ADD CONSTRAINT PK_customer PRIMARY KEY (cno);
