create database dbmysql3;
use dbmysql3;
create table customers( cid int(10),cname varchar (20) not null unique,
age int(10) check (age>20),address varchar(10) not null default 'kspm',
salary int(5)default 5000,check (salary>0),primary key(cid));
desc customers;
insert into customers(cid,cname,age) values(1,'shri',23);
select * from customers;
insert into customers(cid,cname,age) values(2,'kani',24);
insert into customers(cid,cname,age) values(3,'gowri',22);
use dbmysql3;
create table product (id int(5),name varchar(10) not null unique,pid int(10));
desc product;
select * from product;
insert into product(id,name,pid) values(1,'dairymilk',112);
insert into customers(id,name,pid) values(2,'snikkers',123);
insert into customers(id,name,pid) values(3,'milky',223);
use  dbmysql3;
create table student (rollno int(5),name varchar(10),address varchar(10),phone int(10),age int (5));
desc student;
select * from student;
insert into student values ( 1,'harish','delhi',999999999,18);
insert into student values ( 2,'pratik','bihar',888888888,19);
insert into student values ( 3,'riyanka','siliguri',777777777,20);
insert into student values ( 4,'deep','ramnagar',666666666,18);
insert into student values ( 5,'shri','tvm',555555555,19);
insert into student values ( 6,'kani','mumbai',444444444,20);
insert into student values ( 7,'harini','tvm',333333333,18);
insert into student values ( 8,'hrithik','alipur',222222222,19);
use dbmysql3;
create table studentcourse( courseid int(5),rollno int (5));
desc studentcourse;
select * from studentcourse;
insert into studentcourse values (1,1);
insert into studentcourse values (2,2);
insert into studentcourse values (2,3);
insert into studentcourse values (3,4);
insert into studentcourse values (1,5);
insert into studentcourse values (4,9);
insert into studentcourse values (5,10);
insert into studentcourse values (4,11);
