use  dbmysql;
create table employee(eno int(10), ename varchar(20),ecity varchar(20),esalary int(10),edesignation varchar(20));
desc employee;
insert into employee values(1,'deva','chennai',30000,'software developer');
insert into employee values(2,'dharshini','trichy',25000,'analyst');
insert into employee values(3,'bharathi','kanchipuram',40000,'HR');
insert into employee values(4,'seshu','tvmalai',38000,'Manager');
insert into employee values(5,'viji','coimbatore',33000,'assistant manager');
select * from employee;
alter table employee add edeg varchar(10);
alter table employee modify eno int primary key;
alter table employee drop column ecity;
delete from employee where eno=5;
update employee set ename='subi',edeg='MBA' where eno=5;
create user user identified by 'subiksharoot';
insert into employee values(6,'viji',33000,'assistant manager');
insert into employee (eno,ename)values(6,'subiksha');
update employee set esalary=28000 where eno=6;
commit;
update employee set edeg='B.Tech';
savepoint A;
insert into employee values(7,'vijayalakshmi',30000,'HR','M.COM');
rollback ;
select eno,ename from employee;
select 2+6 as addition;
select 5-2 as subtraction;
select 6*2 as multiplication;
select 10/2 as division;
select distinct ename from employee;
select count(ename) as countemployee from employee;
select max(esalary) as employeemaxsalary from employee;
select min(esalary) as employeeminsalary from employee;
select sum(esalary) as employeesumsalary from employee ;
select avg(esalary) as employeeaverage from employee;
select now();
SELECT DATE_FORMAT(CURDATE(), '%m/%d/%Y') today;
select * from employee where esalary>30000;
select * from employee where esalary<30000;
select * from employee where esalary=30000;
select * from employee where esalary!=30000;
alter table employee add ecity varchar(10);
update employee set ecity='chennai' where eno=1;
update employee set ecity='chennai' where eno=2;
select ename from employee where ename like 'd%';
select eno,ename from employee order by ename desc;
select ename,sum(esalary)from employee group by ename;
insert into employee values(8,'usha',20000,'HR','BBA');
select ename,min(esalary)from employee group by esalary;
insert into employee values(9,'moulei',30000,'ATL','MSC');
select ecity,count(*)from employee group by ecity order by count(*) desc;
