use  dbmysql;
create table student(sno int(10), sname varchar(20),scity varchar(20));
desc student;
insert into student values(1,'deva','chennai');
insert into student values(2,'dharshini','trichy');
insert into student values(3,'bharathi','kanchipuram');
insert into student values(4,'seshu','tvmalai');
insert into student values(5,'viji','coimbatore');
select * from student;
alter table student as stud;
alter table stud add sdeg varchar(10);
alter table stud modify sno int primary key;
alter table stud drop column scity;
delete from stud where sno=5;
update student set sname='subi',sdeg='MBA' where eno=5;
create user user identified by 'subiksharoot';
grant privileges_names on object to user;
insert into student (sno,sname)values(6,'subiksha');
update stud set age=28000 where sno=6;
commit;
update stud set edeg='B.Tech';
savepoint A;
insert into stud values(7,'vijayalakshmi');
rollback ;
select * from stud;
select 2+6 as addition;
select 5-2 as subtraction;
select 6*2 as multiplication;
select 10/2 as division;
select * from stud where sname='baru' and age=20;
select * from stud where age between 20 and 25;
select * from stud where sname in('deva','dharshini');
select * from stud where sno in(1,3);
select sname from stud where sname like 'd%';
select distinct age from stud;
select count(sname) as countstudent from stud;
select max(age) as studentmaxage from stud;
select min(age) as studentminage from stud;
select sum(age) as studentsumage from stud;
select avg(age) as studentaverage from stud;
select curdate();
select curtime();
select now();
SELECT DATE_FORMAT(CURDATE(), '%m/%d/%Y') today;
select * from stud where age<25;
select * from stud where age>19;
select * from stud where age=22;
select * from stud where age!=23;

